name = input("Hey whats your name: ")
print("We want to know if you like Pizza!")
print()
print("Do you like Pizza " + name + "?")
answer = input()
print("Great! You said " + answer + "!")
print("Let's eat some Pizza today")